# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2019.3.3\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2019.3.3\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\GitHub\CGCourse-RT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\GitHub\CGCourse-RT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2019.3.3\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2019.3.3\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\GitHub\CGCourse-RT\CMakeFiles D:\GitHub\CGCourse-RT\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\GitHub\CGCourse-RT\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cg

# Build rule for target.
cg: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 cg
.PHONY : cg

# fast build rule for target.
cg/fast:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/build
.PHONY : cg/fast

#=============================================================================
# Target rules for targets named mt_algorithm_test

# Build rule for target.
mt_algorithm_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 mt_algorithm_test
.PHONY : mt_algorithm_test

# fast build rule for target.
mt_algorithm_test/fast:
	$(MAKE) -f CMakeFiles\mt_algorithm_test.dir\build.make CMakeFiles/mt_algorithm_test.dir/build
.PHONY : mt_algorithm_test/fast

#=============================================================================
# Target rules for targets named ray_generation_test

# Build rule for target.
ray_generation_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ray_generation_test
.PHONY : ray_generation_test

# fast build rule for target.
ray_generation_test/fast:
	$(MAKE) -f CMakeFiles\ray_generation_test.dir\build.make CMakeFiles/ray_generation_test.dir/build
.PHONY : ray_generation_test/fast

#=============================================================================
# Target rules for targets named ray_generation

# Build rule for target.
ray_generation: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ray_generation
.PHONY : ray_generation

# fast build rule for target.
ray_generation/fast:
	$(MAKE) -f CMakeFiles\ray_generation.dir\build.make CMakeFiles/ray_generation.dir/build
.PHONY : ray_generation/fast

#=============================================================================
# Target rules for targets named lighting_test

# Build rule for target.
lighting_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 lighting_test
.PHONY : lighting_test

# fast build rule for target.
lighting_test/fast:
	$(MAKE) -f CMakeFiles\lighting_test.dir\build.make CMakeFiles/lighting_test.dir/build
.PHONY : lighting_test/fast

#=============================================================================
# Target rules for targets named mt_algorithm_main

# Build rule for target.
mt_algorithm_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 mt_algorithm_main
.PHONY : mt_algorithm_main

# fast build rule for target.
mt_algorithm_main/fast:
	$(MAKE) -f CMakeFiles\mt_algorithm_main.dir\build.make CMakeFiles/mt_algorithm_main.dir/build
.PHONY : mt_algorithm_main/fast

#=============================================================================
# Target rules for targets named lighting_main

# Build rule for target.
lighting_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 lighting_main
.PHONY : lighting_main

# fast build rule for target.
lighting_main/fast:
	$(MAKE) -f CMakeFiles\lighting_main.dir\build.make CMakeFiles/lighting_main.dir/build
.PHONY : lighting_main/fast

#=============================================================================
# Target rules for targets named shadowray_main

# Build rule for target.
shadowray_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 shadowray_main
.PHONY : shadowray_main

# fast build rule for target.
shadowray_main/fast:
	$(MAKE) -f CMakeFiles\shadowray_main.dir\build.make CMakeFiles/shadowray_main.dir/build
.PHONY : shadowray_main/fast

#=============================================================================
# Target rules for targets named shadowray_test

# Build rule for target.
shadowray_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 shadowray_test
.PHONY : shadowray_test

# fast build rule for target.
shadowray_test/fast:
	$(MAKE) -f CMakeFiles\shadowray_test.dir\build.make CMakeFiles/shadowray_test.dir/build
.PHONY : shadowray_test/fast

#=============================================================================
# Target rules for targets named reflection

# Build rule for target.
reflection: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 reflection
.PHONY : reflection

# fast build rule for target.
reflection/fast:
	$(MAKE) -f CMakeFiles\reflection.dir\build.make CMakeFiles/reflection.dir/build
.PHONY : reflection/fast

#=============================================================================
# Target rules for targets named reflection_test

# Build rule for target.
reflection_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 reflection_test
.PHONY : reflection_test

# fast build rule for target.
reflection_test/fast:
	$(MAKE) -f CMakeFiles\reflection_test.dir\build.make CMakeFiles/reflection_test.dir/build
.PHONY : reflection_test/fast

#=============================================================================
# Target rules for targets named refraction

# Build rule for target.
refraction: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 refraction
.PHONY : refraction

# fast build rule for target.
refraction/fast:
	$(MAKE) -f CMakeFiles\refraction.dir\build.make CMakeFiles/refraction.dir/build
.PHONY : refraction/fast

#=============================================================================
# Target rules for targets named refraction_test

# Build rule for target.
refraction_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 refraction_test
.PHONY : refraction_test

# fast build rule for target.
refraction_test/fast:
	$(MAKE) -f CMakeFiles\refraction_test.dir\build.make CMakeFiles/refraction_test.dir/build
.PHONY : refraction_test/fast

#=============================================================================
# Target rules for targets named aa

# Build rule for target.
aa: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 aa
.PHONY : aa

# fast build rule for target.
aa/fast:
	$(MAKE) -f CMakeFiles\aa.dir\build.make CMakeFiles/aa.dir/build
.PHONY : aa/fast

#=============================================================================
# Target rules for targets named aa_test

# Build rule for target.
aa_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 aa_test
.PHONY : aa_test

# fast build rule for target.
aa_test/fast:
	$(MAKE) -f CMakeFiles\aa_test.dir\build.make CMakeFiles/aa_test.dir/build
.PHONY : aa_test/fast

#=============================================================================
# Target rules for targets named aabb

# Build rule for target.
aabb: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 aabb
.PHONY : aabb

# fast build rule for target.
aabb/fast:
	$(MAKE) -f CMakeFiles\aabb.dir\build.make CMakeFiles/aabb.dir/build
.PHONY : aabb/fast

#=============================================================================
# Target rules for targets named aabb_test

# Build rule for target.
aabb_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 aabb_test
.PHONY : aabb_test

# fast build rule for target.
aabb_test/fast:
	$(MAKE) -f CMakeFiles\aabb_test.dir\build.make CMakeFiles/aabb_test.dir/build
.PHONY : aabb_test/fast

#=============================================================================
# Target rules for targets named bvh

# Build rule for target.
bvh: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 bvh
.PHONY : bvh

# fast build rule for target.
bvh/fast:
	$(MAKE) -f CMakeFiles\bvh.dir\build.make CMakeFiles/bvh.dir/build
.PHONY : bvh/fast

#=============================================================================
# Target rules for targets named bvh_test

# Build rule for target.
bvh_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 bvh_test
.PHONY : bvh_test

# fast build rule for target.
bvh_test/fast:
	$(MAKE) -f CMakeFiles\bvh_test.dir\build.make CMakeFiles/bvh_test.dir/build
.PHONY : bvh_test/fast

#=============================================================================
# Target rules for targets named denoising

# Build rule for target.
denoising: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 denoising
.PHONY : denoising

# fast build rule for target.
denoising/fast:
	$(MAKE) -f CMakeFiles\denoising.dir\build.make CMakeFiles/denoising.dir/build
.PHONY : denoising/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyMemoryCheck.dir\build.make lib/catch2/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\Experimental.dir\build.make lib/catch2/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlySubmit.dir\build.make lib/catch2/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyConfigure.dir\build.make lib/catch2/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyBuild.dir\build.make lib/catch2/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyStart.dir\build.make lib/catch2/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\Continuous.dir\build.make lib/catch2/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyTest.dir\build.make lib/catch2/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\Nightly.dir\build.make lib/catch2/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyUpdate.dir\build.make lib/catch2/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyCoverage.dir\build.make lib/catch2/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\NightlyMemCheck.dir\build.make lib/catch2/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalBuild.dir\build.make lib/catch2/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalStart.dir\build.make lib/catch2/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalUpdate.dir\build.make lib/catch2/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousMemCheck.dir\build.make lib/catch2/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalConfigure.dir\build.make lib/catch2/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalTest.dir\build.make lib/catch2/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalCoverage.dir\build.make lib/catch2/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalMemCheck.dir\build.make lib/catch2/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ExperimentalSubmit.dir\build.make lib/catch2/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousStart.dir\build.make lib/catch2/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousUpdate.dir\build.make lib/catch2/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousSubmit.dir\build.make lib/catch2/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousConfigure.dir\build.make lib/catch2/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousBuild.dir\build.make lib/catch2/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousTest.dir\build.make lib/catch2/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f lib\catch2\CMakeFiles\ContinuousCoverage.dir\build.make lib/catch2/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

src/aabb.obj: src/aabb.cpp.obj

.PHONY : src/aabb.obj

# target to build an object file
src/aabb.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/aabb.cpp.obj
.PHONY : src/aabb.cpp.obj

src/aabb.i: src/aabb.cpp.i

.PHONY : src/aabb.i

# target to preprocess a source file
src/aabb.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/aabb.cpp.i
.PHONY : src/aabb.cpp.i

src/aabb.s: src/aabb.cpp.s

.PHONY : src/aabb.s

# target to generate assembly for a file
src/aabb.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/aabb.cpp.s
.PHONY : src/aabb.cpp.s

src/aabb_main.obj: src/aabb_main.cpp.obj

.PHONY : src/aabb_main.obj

# target to build an object file
src/aabb_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/aabb_main.cpp.obj
	$(MAKE) -f CMakeFiles\aabb.dir\build.make CMakeFiles/aabb.dir/src/aabb_main.cpp.obj
.PHONY : src/aabb_main.cpp.obj

src/aabb_main.i: src/aabb_main.cpp.i

.PHONY : src/aabb_main.i

# target to preprocess a source file
src/aabb_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/aabb_main.cpp.i
	$(MAKE) -f CMakeFiles\aabb.dir\build.make CMakeFiles/aabb.dir/src/aabb_main.cpp.i
.PHONY : src/aabb_main.cpp.i

src/aabb_main.s: src/aabb_main.cpp.s

.PHONY : src/aabb_main.s

# target to generate assembly for a file
src/aabb_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/aabb_main.cpp.s
	$(MAKE) -f CMakeFiles\aabb.dir\build.make CMakeFiles/aabb.dir/src/aabb_main.cpp.s
.PHONY : src/aabb_main.cpp.s

src/anti_aliasing.obj: src/anti_aliasing.cpp.obj

.PHONY : src/anti_aliasing.obj

# target to build an object file
src/anti_aliasing.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/anti_aliasing.cpp.obj
.PHONY : src/anti_aliasing.cpp.obj

src/anti_aliasing.i: src/anti_aliasing.cpp.i

.PHONY : src/anti_aliasing.i

# target to preprocess a source file
src/anti_aliasing.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/anti_aliasing.cpp.i
.PHONY : src/anti_aliasing.cpp.i

src/anti_aliasing.s: src/anti_aliasing.cpp.s

.PHONY : src/anti_aliasing.s

# target to generate assembly for a file
src/anti_aliasing.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/anti_aliasing.cpp.s
.PHONY : src/anti_aliasing.cpp.s

src/anti_aliasing_main.obj: src/anti_aliasing_main.cpp.obj

.PHONY : src/anti_aliasing_main.obj

# target to build an object file
src/anti_aliasing_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/anti_aliasing_main.cpp.obj
	$(MAKE) -f CMakeFiles\aa.dir\build.make CMakeFiles/aa.dir/src/anti_aliasing_main.cpp.obj
.PHONY : src/anti_aliasing_main.cpp.obj

src/anti_aliasing_main.i: src/anti_aliasing_main.cpp.i

.PHONY : src/anti_aliasing_main.i

# target to preprocess a source file
src/anti_aliasing_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/anti_aliasing_main.cpp.i
	$(MAKE) -f CMakeFiles\aa.dir\build.make CMakeFiles/aa.dir/src/anti_aliasing_main.cpp.i
.PHONY : src/anti_aliasing_main.cpp.i

src/anti_aliasing_main.s: src/anti_aliasing_main.cpp.s

.PHONY : src/anti_aliasing_main.s

# target to generate assembly for a file
src/anti_aliasing_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/anti_aliasing_main.cpp.s
	$(MAKE) -f CMakeFiles\aa.dir\build.make CMakeFiles/aa.dir/src/anti_aliasing_main.cpp.s
.PHONY : src/anti_aliasing_main.cpp.s

src/bvh.obj: src/bvh.cpp.obj

.PHONY : src/bvh.obj

# target to build an object file
src/bvh.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/bvh.cpp.obj
.PHONY : src/bvh.cpp.obj

src/bvh.i: src/bvh.cpp.i

.PHONY : src/bvh.i

# target to preprocess a source file
src/bvh.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/bvh.cpp.i
.PHONY : src/bvh.cpp.i

src/bvh.s: src/bvh.cpp.s

.PHONY : src/bvh.s

# target to generate assembly for a file
src/bvh.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/bvh.cpp.s
.PHONY : src/bvh.cpp.s

src/bvh_main.obj: src/bvh_main.cpp.obj

.PHONY : src/bvh_main.obj

# target to build an object file
src/bvh_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/bvh_main.cpp.obj
	$(MAKE) -f CMakeFiles\bvh.dir\build.make CMakeFiles/bvh.dir/src/bvh_main.cpp.obj
.PHONY : src/bvh_main.cpp.obj

src/bvh_main.i: src/bvh_main.cpp.i

.PHONY : src/bvh_main.i

# target to preprocess a source file
src/bvh_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/bvh_main.cpp.i
	$(MAKE) -f CMakeFiles\bvh.dir\build.make CMakeFiles/bvh.dir/src/bvh_main.cpp.i
.PHONY : src/bvh_main.cpp.i

src/bvh_main.s: src/bvh_main.cpp.s

.PHONY : src/bvh_main.s

# target to generate assembly for a file
src/bvh_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/bvh_main.cpp.s
	$(MAKE) -f CMakeFiles\bvh.dir\build.make CMakeFiles/bvh.dir/src/bvh_main.cpp.s
.PHONY : src/bvh_main.cpp.s

src/denoising.obj: src/denoising.cpp.obj

.PHONY : src/denoising.obj

# target to build an object file
src/denoising.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/denoising.cpp.obj
.PHONY : src/denoising.cpp.obj

src/denoising.i: src/denoising.cpp.i

.PHONY : src/denoising.i

# target to preprocess a source file
src/denoising.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/denoising.cpp.i
.PHONY : src/denoising.cpp.i

src/denoising.s: src/denoising.cpp.s

.PHONY : src/denoising.s

# target to generate assembly for a file
src/denoising.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/denoising.cpp.s
.PHONY : src/denoising.cpp.s

src/denoising_main.obj: src/denoising_main.cpp.obj

.PHONY : src/denoising_main.obj

# target to build an object file
src/denoising_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/denoising_main.cpp.obj
	$(MAKE) -f CMakeFiles\denoising.dir\build.make CMakeFiles/denoising.dir/src/denoising_main.cpp.obj
.PHONY : src/denoising_main.cpp.obj

src/denoising_main.i: src/denoising_main.cpp.i

.PHONY : src/denoising_main.i

# target to preprocess a source file
src/denoising_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/denoising_main.cpp.i
	$(MAKE) -f CMakeFiles\denoising.dir\build.make CMakeFiles/denoising.dir/src/denoising_main.cpp.i
.PHONY : src/denoising_main.cpp.i

src/denoising_main.s: src/denoising_main.cpp.s

.PHONY : src/denoising_main.s

# target to generate assembly for a file
src/denoising_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/denoising_main.cpp.s
	$(MAKE) -f CMakeFiles\denoising.dir\build.make CMakeFiles/denoising.dir/src/denoising_main.cpp.s
.PHONY : src/denoising_main.cpp.s

src/lighting.obj: src/lighting.cpp.obj

.PHONY : src/lighting.obj

# target to build an object file
src/lighting.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/lighting.cpp.obj
.PHONY : src/lighting.cpp.obj

src/lighting.i: src/lighting.cpp.i

.PHONY : src/lighting.i

# target to preprocess a source file
src/lighting.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/lighting.cpp.i
.PHONY : src/lighting.cpp.i

src/lighting.s: src/lighting.cpp.s

.PHONY : src/lighting.s

# target to generate assembly for a file
src/lighting.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/lighting.cpp.s
.PHONY : src/lighting.cpp.s

src/lighting_main.obj: src/lighting_main.cpp.obj

.PHONY : src/lighting_main.obj

# target to build an object file
src/lighting_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/lighting_main.cpp.obj
	$(MAKE) -f CMakeFiles\lighting_main.dir\build.make CMakeFiles/lighting_main.dir/src/lighting_main.cpp.obj
.PHONY : src/lighting_main.cpp.obj

src/lighting_main.i: src/lighting_main.cpp.i

.PHONY : src/lighting_main.i

# target to preprocess a source file
src/lighting_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/lighting_main.cpp.i
	$(MAKE) -f CMakeFiles\lighting_main.dir\build.make CMakeFiles/lighting_main.dir/src/lighting_main.cpp.i
.PHONY : src/lighting_main.cpp.i

src/lighting_main.s: src/lighting_main.cpp.s

.PHONY : src/lighting_main.s

# target to generate assembly for a file
src/lighting_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/lighting_main.cpp.s
	$(MAKE) -f CMakeFiles\lighting_main.dir\build.make CMakeFiles/lighting_main.dir/src/lighting_main.cpp.s
.PHONY : src/lighting_main.cpp.s

src/mt_algorithm.obj: src/mt_algorithm.cpp.obj

.PHONY : src/mt_algorithm.obj

# target to build an object file
src/mt_algorithm.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/mt_algorithm.cpp.obj
.PHONY : src/mt_algorithm.cpp.obj

src/mt_algorithm.i: src/mt_algorithm.cpp.i

.PHONY : src/mt_algorithm.i

# target to preprocess a source file
src/mt_algorithm.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/mt_algorithm.cpp.i
.PHONY : src/mt_algorithm.cpp.i

src/mt_algorithm.s: src/mt_algorithm.cpp.s

.PHONY : src/mt_algorithm.s

# target to generate assembly for a file
src/mt_algorithm.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/mt_algorithm.cpp.s
.PHONY : src/mt_algorithm.cpp.s

src/mt_algorithm_main.obj: src/mt_algorithm_main.cpp.obj

.PHONY : src/mt_algorithm_main.obj

# target to build an object file
src/mt_algorithm_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/mt_algorithm_main.cpp.obj
	$(MAKE) -f CMakeFiles\mt_algorithm_main.dir\build.make CMakeFiles/mt_algorithm_main.dir/src/mt_algorithm_main.cpp.obj
.PHONY : src/mt_algorithm_main.cpp.obj

src/mt_algorithm_main.i: src/mt_algorithm_main.cpp.i

.PHONY : src/mt_algorithm_main.i

# target to preprocess a source file
src/mt_algorithm_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/mt_algorithm_main.cpp.i
	$(MAKE) -f CMakeFiles\mt_algorithm_main.dir\build.make CMakeFiles/mt_algorithm_main.dir/src/mt_algorithm_main.cpp.i
.PHONY : src/mt_algorithm_main.cpp.i

src/mt_algorithm_main.s: src/mt_algorithm_main.cpp.s

.PHONY : src/mt_algorithm_main.s

# target to generate assembly for a file
src/mt_algorithm_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/mt_algorithm_main.cpp.s
	$(MAKE) -f CMakeFiles\mt_algorithm_main.dir\build.make CMakeFiles/mt_algorithm_main.dir/src/mt_algorithm_main.cpp.s
.PHONY : src/mt_algorithm_main.cpp.s

src/ray_generation.obj: src/ray_generation.cpp.obj

.PHONY : src/ray_generation.obj

# target to build an object file
src/ray_generation.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/ray_generation.cpp.obj
.PHONY : src/ray_generation.cpp.obj

src/ray_generation.i: src/ray_generation.cpp.i

.PHONY : src/ray_generation.i

# target to preprocess a source file
src/ray_generation.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/ray_generation.cpp.i
.PHONY : src/ray_generation.cpp.i

src/ray_generation.s: src/ray_generation.cpp.s

.PHONY : src/ray_generation.s

# target to generate assembly for a file
src/ray_generation.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/ray_generation.cpp.s
.PHONY : src/ray_generation.cpp.s

src/ray_generation_main.obj: src/ray_generation_main.cpp.obj

.PHONY : src/ray_generation_main.obj

# target to build an object file
src/ray_generation_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/ray_generation_main.cpp.obj
	$(MAKE) -f CMakeFiles\ray_generation.dir\build.make CMakeFiles/ray_generation.dir/src/ray_generation_main.cpp.obj
.PHONY : src/ray_generation_main.cpp.obj

src/ray_generation_main.i: src/ray_generation_main.cpp.i

.PHONY : src/ray_generation_main.i

# target to preprocess a source file
src/ray_generation_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/ray_generation_main.cpp.i
	$(MAKE) -f CMakeFiles\ray_generation.dir\build.make CMakeFiles/ray_generation.dir/src/ray_generation_main.cpp.i
.PHONY : src/ray_generation_main.cpp.i

src/ray_generation_main.s: src/ray_generation_main.cpp.s

.PHONY : src/ray_generation_main.s

# target to generate assembly for a file
src/ray_generation_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/ray_generation_main.cpp.s
	$(MAKE) -f CMakeFiles\ray_generation.dir\build.make CMakeFiles/ray_generation.dir/src/ray_generation_main.cpp.s
.PHONY : src/ray_generation_main.cpp.s

src/reflection.obj: src/reflection.cpp.obj

.PHONY : src/reflection.obj

# target to build an object file
src/reflection.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/reflection.cpp.obj
.PHONY : src/reflection.cpp.obj

src/reflection.i: src/reflection.cpp.i

.PHONY : src/reflection.i

# target to preprocess a source file
src/reflection.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/reflection.cpp.i
.PHONY : src/reflection.cpp.i

src/reflection.s: src/reflection.cpp.s

.PHONY : src/reflection.s

# target to generate assembly for a file
src/reflection.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/reflection.cpp.s
.PHONY : src/reflection.cpp.s

src/reflection_main.obj: src/reflection_main.cpp.obj

.PHONY : src/reflection_main.obj

# target to build an object file
src/reflection_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/reflection_main.cpp.obj
	$(MAKE) -f CMakeFiles\reflection.dir\build.make CMakeFiles/reflection.dir/src/reflection_main.cpp.obj
.PHONY : src/reflection_main.cpp.obj

src/reflection_main.i: src/reflection_main.cpp.i

.PHONY : src/reflection_main.i

# target to preprocess a source file
src/reflection_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/reflection_main.cpp.i
	$(MAKE) -f CMakeFiles\reflection.dir\build.make CMakeFiles/reflection.dir/src/reflection_main.cpp.i
.PHONY : src/reflection_main.cpp.i

src/reflection_main.s: src/reflection_main.cpp.s

.PHONY : src/reflection_main.s

# target to generate assembly for a file
src/reflection_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/reflection_main.cpp.s
	$(MAKE) -f CMakeFiles\reflection.dir\build.make CMakeFiles/reflection.dir/src/reflection_main.cpp.s
.PHONY : src/reflection_main.cpp.s

src/refraction.obj: src/refraction.cpp.obj

.PHONY : src/refraction.obj

# target to build an object file
src/refraction.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/refraction.cpp.obj
.PHONY : src/refraction.cpp.obj

src/refraction.i: src/refraction.cpp.i

.PHONY : src/refraction.i

# target to preprocess a source file
src/refraction.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/refraction.cpp.i
.PHONY : src/refraction.cpp.i

src/refraction.s: src/refraction.cpp.s

.PHONY : src/refraction.s

# target to generate assembly for a file
src/refraction.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/refraction.cpp.s
.PHONY : src/refraction.cpp.s

src/refraction_main.obj: src/refraction_main.cpp.obj

.PHONY : src/refraction_main.obj

# target to build an object file
src/refraction_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/refraction_main.cpp.obj
	$(MAKE) -f CMakeFiles\refraction.dir\build.make CMakeFiles/refraction.dir/src/refraction_main.cpp.obj
.PHONY : src/refraction_main.cpp.obj

src/refraction_main.i: src/refraction_main.cpp.i

.PHONY : src/refraction_main.i

# target to preprocess a source file
src/refraction_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/refraction_main.cpp.i
	$(MAKE) -f CMakeFiles\refraction.dir\build.make CMakeFiles/refraction.dir/src/refraction_main.cpp.i
.PHONY : src/refraction_main.cpp.i

src/refraction_main.s: src/refraction_main.cpp.s

.PHONY : src/refraction_main.s

# target to generate assembly for a file
src/refraction_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/refraction_main.cpp.s
	$(MAKE) -f CMakeFiles\refraction.dir\build.make CMakeFiles/refraction.dir/src/refraction_main.cpp.s
.PHONY : src/refraction_main.cpp.s

src/shadow_rays.obj: src/shadow_rays.cpp.obj

.PHONY : src/shadow_rays.obj

# target to build an object file
src/shadow_rays.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/shadow_rays.cpp.obj
.PHONY : src/shadow_rays.cpp.obj

src/shadow_rays.i: src/shadow_rays.cpp.i

.PHONY : src/shadow_rays.i

# target to preprocess a source file
src/shadow_rays.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/shadow_rays.cpp.i
.PHONY : src/shadow_rays.cpp.i

src/shadow_rays.s: src/shadow_rays.cpp.s

.PHONY : src/shadow_rays.s

# target to generate assembly for a file
src/shadow_rays.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/shadow_rays.cpp.s
.PHONY : src/shadow_rays.cpp.s

src/shadow_rays_main.obj: src/shadow_rays_main.cpp.obj

.PHONY : src/shadow_rays_main.obj

# target to build an object file
src/shadow_rays_main.cpp.obj:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/shadow_rays_main.cpp.obj
	$(MAKE) -f CMakeFiles\shadowray_main.dir\build.make CMakeFiles/shadowray_main.dir/src/shadow_rays_main.cpp.obj
.PHONY : src/shadow_rays_main.cpp.obj

src/shadow_rays_main.i: src/shadow_rays_main.cpp.i

.PHONY : src/shadow_rays_main.i

# target to preprocess a source file
src/shadow_rays_main.cpp.i:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/shadow_rays_main.cpp.i
	$(MAKE) -f CMakeFiles\shadowray_main.dir\build.make CMakeFiles/shadowray_main.dir/src/shadow_rays_main.cpp.i
.PHONY : src/shadow_rays_main.cpp.i

src/shadow_rays_main.s: src/shadow_rays_main.cpp.s

.PHONY : src/shadow_rays_main.s

# target to generate assembly for a file
src/shadow_rays_main.cpp.s:
	$(MAKE) -f CMakeFiles\cg.dir\build.make CMakeFiles/cg.dir/src/shadow_rays_main.cpp.s
	$(MAKE) -f CMakeFiles\shadowray_main.dir\build.make CMakeFiles/shadowray_main.dir/src/shadow_rays_main.cpp.s
.PHONY : src/shadow_rays_main.cpp.s

tests/aabb_tests.obj: tests/aabb_tests.cpp.obj

.PHONY : tests/aabb_tests.obj

# target to build an object file
tests/aabb_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\aabb_test.dir\build.make CMakeFiles/aabb_test.dir/tests/aabb_tests.cpp.obj
.PHONY : tests/aabb_tests.cpp.obj

tests/aabb_tests.i: tests/aabb_tests.cpp.i

.PHONY : tests/aabb_tests.i

# target to preprocess a source file
tests/aabb_tests.cpp.i:
	$(MAKE) -f CMakeFiles\aabb_test.dir\build.make CMakeFiles/aabb_test.dir/tests/aabb_tests.cpp.i
.PHONY : tests/aabb_tests.cpp.i

tests/aabb_tests.s: tests/aabb_tests.cpp.s

.PHONY : tests/aabb_tests.s

# target to generate assembly for a file
tests/aabb_tests.cpp.s:
	$(MAKE) -f CMakeFiles\aabb_test.dir\build.make CMakeFiles/aabb_test.dir/tests/aabb_tests.cpp.s
.PHONY : tests/aabb_tests.cpp.s

tests/anti_aliasing_tests.obj: tests/anti_aliasing_tests.cpp.obj

.PHONY : tests/anti_aliasing_tests.obj

# target to build an object file
tests/anti_aliasing_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\aa_test.dir\build.make CMakeFiles/aa_test.dir/tests/anti_aliasing_tests.cpp.obj
.PHONY : tests/anti_aliasing_tests.cpp.obj

tests/anti_aliasing_tests.i: tests/anti_aliasing_tests.cpp.i

.PHONY : tests/anti_aliasing_tests.i

# target to preprocess a source file
tests/anti_aliasing_tests.cpp.i:
	$(MAKE) -f CMakeFiles\aa_test.dir\build.make CMakeFiles/aa_test.dir/tests/anti_aliasing_tests.cpp.i
.PHONY : tests/anti_aliasing_tests.cpp.i

tests/anti_aliasing_tests.s: tests/anti_aliasing_tests.cpp.s

.PHONY : tests/anti_aliasing_tests.s

# target to generate assembly for a file
tests/anti_aliasing_tests.cpp.s:
	$(MAKE) -f CMakeFiles\aa_test.dir\build.make CMakeFiles/aa_test.dir/tests/anti_aliasing_tests.cpp.s
.PHONY : tests/anti_aliasing_tests.cpp.s

tests/bvh_tests.obj: tests/bvh_tests.cpp.obj

.PHONY : tests/bvh_tests.obj

# target to build an object file
tests/bvh_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\bvh_test.dir\build.make CMakeFiles/bvh_test.dir/tests/bvh_tests.cpp.obj
.PHONY : tests/bvh_tests.cpp.obj

tests/bvh_tests.i: tests/bvh_tests.cpp.i

.PHONY : tests/bvh_tests.i

# target to preprocess a source file
tests/bvh_tests.cpp.i:
	$(MAKE) -f CMakeFiles\bvh_test.dir\build.make CMakeFiles/bvh_test.dir/tests/bvh_tests.cpp.i
.PHONY : tests/bvh_tests.cpp.i

tests/bvh_tests.s: tests/bvh_tests.cpp.s

.PHONY : tests/bvh_tests.s

# target to generate assembly for a file
tests/bvh_tests.cpp.s:
	$(MAKE) -f CMakeFiles\bvh_test.dir\build.make CMakeFiles/bvh_test.dir/tests/bvh_tests.cpp.s
.PHONY : tests/bvh_tests.cpp.s

tests/lighting_tests.obj: tests/lighting_tests.cpp.obj

.PHONY : tests/lighting_tests.obj

# target to build an object file
tests/lighting_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\lighting_test.dir\build.make CMakeFiles/lighting_test.dir/tests/lighting_tests.cpp.obj
.PHONY : tests/lighting_tests.cpp.obj

tests/lighting_tests.i: tests/lighting_tests.cpp.i

.PHONY : tests/lighting_tests.i

# target to preprocess a source file
tests/lighting_tests.cpp.i:
	$(MAKE) -f CMakeFiles\lighting_test.dir\build.make CMakeFiles/lighting_test.dir/tests/lighting_tests.cpp.i
.PHONY : tests/lighting_tests.cpp.i

tests/lighting_tests.s: tests/lighting_tests.cpp.s

.PHONY : tests/lighting_tests.s

# target to generate assembly for a file
tests/lighting_tests.cpp.s:
	$(MAKE) -f CMakeFiles\lighting_test.dir\build.make CMakeFiles/lighting_test.dir/tests/lighting_tests.cpp.s
.PHONY : tests/lighting_tests.cpp.s

tests/mt_algorithm_tests.obj: tests/mt_algorithm_tests.cpp.obj

.PHONY : tests/mt_algorithm_tests.obj

# target to build an object file
tests/mt_algorithm_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\mt_algorithm_test.dir\build.make CMakeFiles/mt_algorithm_test.dir/tests/mt_algorithm_tests.cpp.obj
.PHONY : tests/mt_algorithm_tests.cpp.obj

tests/mt_algorithm_tests.i: tests/mt_algorithm_tests.cpp.i

.PHONY : tests/mt_algorithm_tests.i

# target to preprocess a source file
tests/mt_algorithm_tests.cpp.i:
	$(MAKE) -f CMakeFiles\mt_algorithm_test.dir\build.make CMakeFiles/mt_algorithm_test.dir/tests/mt_algorithm_tests.cpp.i
.PHONY : tests/mt_algorithm_tests.cpp.i

tests/mt_algorithm_tests.s: tests/mt_algorithm_tests.cpp.s

.PHONY : tests/mt_algorithm_tests.s

# target to generate assembly for a file
tests/mt_algorithm_tests.cpp.s:
	$(MAKE) -f CMakeFiles\mt_algorithm_test.dir\build.make CMakeFiles/mt_algorithm_test.dir/tests/mt_algorithm_tests.cpp.s
.PHONY : tests/mt_algorithm_tests.cpp.s

tests/ray_generation_tests.obj: tests/ray_generation_tests.cpp.obj

.PHONY : tests/ray_generation_tests.obj

# target to build an object file
tests/ray_generation_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\ray_generation_test.dir\build.make CMakeFiles/ray_generation_test.dir/tests/ray_generation_tests.cpp.obj
.PHONY : tests/ray_generation_tests.cpp.obj

tests/ray_generation_tests.i: tests/ray_generation_tests.cpp.i

.PHONY : tests/ray_generation_tests.i

# target to preprocess a source file
tests/ray_generation_tests.cpp.i:
	$(MAKE) -f CMakeFiles\ray_generation_test.dir\build.make CMakeFiles/ray_generation_test.dir/tests/ray_generation_tests.cpp.i
.PHONY : tests/ray_generation_tests.cpp.i

tests/ray_generation_tests.s: tests/ray_generation_tests.cpp.s

.PHONY : tests/ray_generation_tests.s

# target to generate assembly for a file
tests/ray_generation_tests.cpp.s:
	$(MAKE) -f CMakeFiles\ray_generation_test.dir\build.make CMakeFiles/ray_generation_test.dir/tests/ray_generation_tests.cpp.s
.PHONY : tests/ray_generation_tests.cpp.s

tests/reflection_tests.obj: tests/reflection_tests.cpp.obj

.PHONY : tests/reflection_tests.obj

# target to build an object file
tests/reflection_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\reflection_test.dir\build.make CMakeFiles/reflection_test.dir/tests/reflection_tests.cpp.obj
.PHONY : tests/reflection_tests.cpp.obj

tests/reflection_tests.i: tests/reflection_tests.cpp.i

.PHONY : tests/reflection_tests.i

# target to preprocess a source file
tests/reflection_tests.cpp.i:
	$(MAKE) -f CMakeFiles\reflection_test.dir\build.make CMakeFiles/reflection_test.dir/tests/reflection_tests.cpp.i
.PHONY : tests/reflection_tests.cpp.i

tests/reflection_tests.s: tests/reflection_tests.cpp.s

.PHONY : tests/reflection_tests.s

# target to generate assembly for a file
tests/reflection_tests.cpp.s:
	$(MAKE) -f CMakeFiles\reflection_test.dir\build.make CMakeFiles/reflection_test.dir/tests/reflection_tests.cpp.s
.PHONY : tests/reflection_tests.cpp.s

tests/refraction_tests.obj: tests/refraction_tests.cpp.obj

.PHONY : tests/refraction_tests.obj

# target to build an object file
tests/refraction_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\refraction_test.dir\build.make CMakeFiles/refraction_test.dir/tests/refraction_tests.cpp.obj
.PHONY : tests/refraction_tests.cpp.obj

tests/refraction_tests.i: tests/refraction_tests.cpp.i

.PHONY : tests/refraction_tests.i

# target to preprocess a source file
tests/refraction_tests.cpp.i:
	$(MAKE) -f CMakeFiles\refraction_test.dir\build.make CMakeFiles/refraction_test.dir/tests/refraction_tests.cpp.i
.PHONY : tests/refraction_tests.cpp.i

tests/refraction_tests.s: tests/refraction_tests.cpp.s

.PHONY : tests/refraction_tests.s

# target to generate assembly for a file
tests/refraction_tests.cpp.s:
	$(MAKE) -f CMakeFiles\refraction_test.dir\build.make CMakeFiles/refraction_test.dir/tests/refraction_tests.cpp.s
.PHONY : tests/refraction_tests.cpp.s

tests/shadow_rays_tests.obj: tests/shadow_rays_tests.cpp.obj

.PHONY : tests/shadow_rays_tests.obj

# target to build an object file
tests/shadow_rays_tests.cpp.obj:
	$(MAKE) -f CMakeFiles\shadowray_test.dir\build.make CMakeFiles/shadowray_test.dir/tests/shadow_rays_tests.cpp.obj
.PHONY : tests/shadow_rays_tests.cpp.obj

tests/shadow_rays_tests.i: tests/shadow_rays_tests.cpp.i

.PHONY : tests/shadow_rays_tests.i

# target to preprocess a source file
tests/shadow_rays_tests.cpp.i:
	$(MAKE) -f CMakeFiles\shadowray_test.dir\build.make CMakeFiles/shadowray_test.dir/tests/shadow_rays_tests.cpp.i
.PHONY : tests/shadow_rays_tests.cpp.i

tests/shadow_rays_tests.s: tests/shadow_rays_tests.cpp.s

.PHONY : tests/shadow_rays_tests.s

# target to generate assembly for a file
tests/shadow_rays_tests.cpp.s:
	$(MAKE) -f CMakeFiles\shadowray_test.dir\build.make CMakeFiles/shadowray_test.dir/tests/shadow_rays_tests.cpp.s
.PHONY : tests/shadow_rays_tests.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... cg
	@echo ... mt_algorithm_test
	@echo ... ray_generation_test
	@echo ... ray_generation
	@echo ... lighting_test
	@echo ... mt_algorithm_main
	@echo ... lighting_main
	@echo ... shadowray_main
	@echo ... shadowray_test
	@echo ... reflection
	@echo ... reflection_test
	@echo ... refraction
	@echo ... refraction_test
	@echo ... aa
	@echo ... aa_test
	@echo ... aabb
	@echo ... aabb_test
	@echo ... bvh
	@echo ... bvh_test
	@echo ... denoising
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... NightlyMemoryCheck
	@echo ... Experimental
	@echo ... NightlySubmit
	@echo ... NightlyConfigure
	@echo ... NightlyBuild
	@echo ... NightlyStart
	@echo ... Continuous
	@echo ... NightlyTest
	@echo ... Nightly
	@echo ... NightlyUpdate
	@echo ... NightlyCoverage
	@echo ... NightlyMemCheck
	@echo ... ExperimentalBuild
	@echo ... ExperimentalStart
	@echo ... ExperimentalUpdate
	@echo ... ContinuousMemCheck
	@echo ... ExperimentalConfigure
	@echo ... ExperimentalTest
	@echo ... ExperimentalCoverage
	@echo ... ExperimentalMemCheck
	@echo ... ExperimentalSubmit
	@echo ... ContinuousStart
	@echo ... ContinuousUpdate
	@echo ... ContinuousSubmit
	@echo ... ContinuousConfigure
	@echo ... ContinuousBuild
	@echo ... ContinuousTest
	@echo ... ContinuousCoverage
	@echo ... src/aabb.obj
	@echo ... src/aabb.i
	@echo ... src/aabb.s
	@echo ... src/aabb_main.obj
	@echo ... src/aabb_main.i
	@echo ... src/aabb_main.s
	@echo ... src/anti_aliasing.obj
	@echo ... src/anti_aliasing.i
	@echo ... src/anti_aliasing.s
	@echo ... src/anti_aliasing_main.obj
	@echo ... src/anti_aliasing_main.i
	@echo ... src/anti_aliasing_main.s
	@echo ... src/bvh.obj
	@echo ... src/bvh.i
	@echo ... src/bvh.s
	@echo ... src/bvh_main.obj
	@echo ... src/bvh_main.i
	@echo ... src/bvh_main.s
	@echo ... src/denoising.obj
	@echo ... src/denoising.i
	@echo ... src/denoising.s
	@echo ... src/denoising_main.obj
	@echo ... src/denoising_main.i
	@echo ... src/denoising_main.s
	@echo ... src/lighting.obj
	@echo ... src/lighting.i
	@echo ... src/lighting.s
	@echo ... src/lighting_main.obj
	@echo ... src/lighting_main.i
	@echo ... src/lighting_main.s
	@echo ... src/mt_algorithm.obj
	@echo ... src/mt_algorithm.i
	@echo ... src/mt_algorithm.s
	@echo ... src/mt_algorithm_main.obj
	@echo ... src/mt_algorithm_main.i
	@echo ... src/mt_algorithm_main.s
	@echo ... src/ray_generation.obj
	@echo ... src/ray_generation.i
	@echo ... src/ray_generation.s
	@echo ... src/ray_generation_main.obj
	@echo ... src/ray_generation_main.i
	@echo ... src/ray_generation_main.s
	@echo ... src/reflection.obj
	@echo ... src/reflection.i
	@echo ... src/reflection.s
	@echo ... src/reflection_main.obj
	@echo ... src/reflection_main.i
	@echo ... src/reflection_main.s
	@echo ... src/refraction.obj
	@echo ... src/refraction.i
	@echo ... src/refraction.s
	@echo ... src/refraction_main.obj
	@echo ... src/refraction_main.i
	@echo ... src/refraction_main.s
	@echo ... src/shadow_rays.obj
	@echo ... src/shadow_rays.i
	@echo ... src/shadow_rays.s
	@echo ... src/shadow_rays_main.obj
	@echo ... src/shadow_rays_main.i
	@echo ... src/shadow_rays_main.s
	@echo ... tests/aabb_tests.obj
	@echo ... tests/aabb_tests.i
	@echo ... tests/aabb_tests.s
	@echo ... tests/anti_aliasing_tests.obj
	@echo ... tests/anti_aliasing_tests.i
	@echo ... tests/anti_aliasing_tests.s
	@echo ... tests/bvh_tests.obj
	@echo ... tests/bvh_tests.i
	@echo ... tests/bvh_tests.s
	@echo ... tests/lighting_tests.obj
	@echo ... tests/lighting_tests.i
	@echo ... tests/lighting_tests.s
	@echo ... tests/mt_algorithm_tests.obj
	@echo ... tests/mt_algorithm_tests.i
	@echo ... tests/mt_algorithm_tests.s
	@echo ... tests/ray_generation_tests.obj
	@echo ... tests/ray_generation_tests.i
	@echo ... tests/ray_generation_tests.s
	@echo ... tests/reflection_tests.obj
	@echo ... tests/reflection_tests.i
	@echo ... tests/reflection_tests.s
	@echo ... tests/refraction_tests.obj
	@echo ... tests/refraction_tests.i
	@echo ... tests/refraction_tests.s
	@echo ... tests/shadow_rays_tests.obj
	@echo ... tests/shadow_rays_tests.i
	@echo ... tests/shadow_rays_tests.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

